name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  get: ^4.6.5
  url_launcher: ^6.2.3
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  emailjs: ^4.0.0
  flutter_dotenv: ^5.1.0
  html: ^0.15.4
  flutter:
    sdk: flutter
  file_saver: ^0.2.14
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  flutter_app_icons: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
      - assets/
      - assets/coin_logo.png
      - .env
      - assets/fonts/
      
  fonts:
    - family: Gruppo
      fonts:
        - asset: assets/fonts/Gruppo-Regular.ttf

    - family: ExpletusSans
      fonts:
        - asset: assets/fonts/ExpletusSans-VariableFont_wght.ttf

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf    
  uses-material-design: true
